clean:
	rm *~ *#* *.bak foo* goo*

www:
	cp Examples.html /cygdrive/c/xampp/htdocs/pa/financial
	cp FI.css /cygdrive/c/xampp/htdocs/pa/financial
	cp FI.html /cygdrive/c/xampp/htdocs/pa/financial
	cp FI.js /cygdrive/c/xampp/htdocs/pa/financial
	cp Instructions.html /cygdrive/c/xampp/htdocs/pa/financial
	cp Makefile /cygdrive/c/xampp/htdocs/pa/financial
	cp bell-323942.mp3 /cygdrive/c/xampp/htdocs/pa/financial
	cp calling-whistle-41861.mp3 /cygdrive/c/xampp/htdocs/pa/financial
	cp church-bells-194653.mp3 /cygdrive/c/xampp/htdocs/pa/financial
	cp math.html /cygdrive/c/xampp/htdocs/pa/financial
	cp math.pdf /cygdrive/c/xampp/htdocs/pa/financial
	cp whistle-slide-down-02-350715.mp3 /cygdrive/c/xampp/htdocs/pa/financial


